name: jujin_app_news
description: A new Flutter project.



dependencies:
  flutter:
    sdk: flutter
 # url_launcher:
#  timeago:
  shared_preferences:
#  intl:
#  intl_translation:
#  html_unescape:

dev_dependencies:
  flutter_test:
    sdk: flutter




# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the Icons class.
  uses-material-design: true
  assets:
   - images/美国.png
   - images/澳大利亚.png
   - images/德国.png
   - images/法国.png
   - images/韩国.png
   - images/加拿大.png
   - images/欧元区.png
   - images/日本.png
   - images/瑞士.png
   - images/台湾.png
   - images/西班牙.png
   - images/希腊.png
   - images/香港.png
   - images/新加坡.png
   - images/新西兰.png
   - images/意大利.png
   - images/英国.png
   - images/中国.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/
  
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
